-- Registro de operaciones

-- MySQL
CREATE TABLE IF NOT EXISTS Registro (
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	Usrs TEXT NOT NULL COMMENT 'Usuario', 
	Oper TEXT NOT NULL COMMENT 'Operación realizada', 
	Tabl TEXT NOT NULL COMMENT 'Tabla afectada', 
	FHRe DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Fecha y hora de operación', 
	RPre LONGTEXT NULL COMMENT 'Datos previos', 
	RPos LONGTEXT NULL COMMENT 'Datos posteriores', 
	PRIMARY KEY (ID)
);
-- SQLite
CREATE TABLE IF NOT EXISTS Registro (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	Usrs TEXT NOT NULL, 
	Oper TEXT NOT NULL, 
	Tabl TEXT NOT NULL, 
	FHRe DATETIME NOT NULL DEFAULT (datetime('now')), 
	RPre LONGTEXT NULL, 
	RPos LONGTEXT NULL
);
-- SQL Server
CREATE TABLE [dbo].[Productos]
(
	[ID] BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	[Usrs] TEXT NOT NULL, 
	[Oper] TEXT NOT NULL, 
	[Tabl] TEXT NOT NULL, 
	[FHRe] DATETIME NOT NULL DEFAULT GETDATE(), 
	[RPre] LONGTEXT NULL, 
	[RPos] LONGTEXT NULL
);

-- Crear TRIGGER para establecer un historial de operaciones INSERT, UPDATE y DELETE en tablas

-- MySQL
CREATE TRIGGER IF NOT EXISTS [TRIGGER] 
AFTER INSERT/UPDATE/DELETE ON [TABLA] 
FOR EACH ROW 
INSERT INTO TAudit (Usrs, Oper, Tabl, RPre, RPos) 
VALUES (
	USER(), '[INSERT/UPDATE/DELETE]', '[TABLA]', 
	CONCAT(
		'[COLUMNA]', OLD.[COLUMNA]
	), 
	CONCAT(
		'[COLUMNA]', NEW.[COLUMNA]
	)
);